INSERT OR REPLACE INTO operation_status VALUES (0, "UNDEFINED", "", 0);
INSERT OR REPLACE INTO operation_status VALUES (1, "OK", "", 0);
INSERT OR REPLACE INTO operation_status VALUES (2, "NOK", "", 0);
INSERT OR REPLACE INTO operation_status VALUES (4, "NOTAVAILABLE", "", 0);
INSERT OR REPLACE INTO operation_status VALUES (5, "REPEATEDOK", "", 0);
INSERT OR REPLACE INTO operation_status VALUES (6, "REPEATEDNOK", "", 0);
INSERT OR REPLACE INTO operation_status VALUES (9, "WAITING", "", 0);
INSERT OR REPLACE INTO operation_status VALUES (10, "INTERRUPTED", "", 0);
INSERT OR REPLACE INTO operation_status VALUES (11, "REPEATEDINTERRUPTED", "", 0);
INSERT OR REPLACE INTO operation_status VALUES (99, "VALUEERROR", "", 0);
INSERT OR REPLACE INTO operation_status VALUES (1000, "Brak", "", 0);
INSERT OR REPLACE INTO operation_status VALUES (1001, "Prasowanie tulejek OK", "", 0);
INSERT OR REPLACE INTO operation_status VALUES (1002, "Prasowanie tulejek NOK", "", 0);
INSERT OR REPLACE INTO operation_status VALUES (2000, "Brak", "", 0);
INSERT OR REPLACE INTO operation_status VALUES (2001, "Smarowanie OK", "", 0);
INSERT OR REPLACE INTO operation_status VALUES (2002, "Smarowanie NOK", "", 0);
INSERT OR REPLACE INTO operation_status VALUES (3000, "Brak", "", 0);
INSERT OR REPLACE INTO operation_status VALUES (3001, "Referencjonowanie Promessa NOK", "", 4);
INSERT OR REPLACE INTO operation_status VALUES (3002, "Referencjonowanie Promessa NOK", "", 5);
INSERT OR REPLACE INTO operation_status VALUES (3011, "Wciskanie kołka pozycja OK", "", 4);
INSERT OR REPLACE INTO operation_status VALUES (3012, "Wciskanie kołka pozycja NOK (za mała)", "", 4);
INSERT OR REPLACE INTO operation_status VALUES (3013, "Wciskanie kołka pozycja NOK (za duża)", "", 4);
INSERT OR REPLACE INTO operation_status VALUES (3031, "Wciskanie kołka siła OK", "", 5);
INSERT OR REPLACE INTO operation_status VALUES (3032, "Wciskanie kołka siła NOK (za mała)", "", 5);
INSERT OR REPLACE INTO operation_status VALUES (3033, "Wciskanie kołka siła NOK (za duża)", "", 5);
INSERT OR REPLACE INTO operation_status VALUES (4000, "Brak", "", 0);
INSERT OR REPLACE INTO operation_status VALUES (4001, "Pierwszy test szczelności OK", "", 6);
INSERT OR REPLACE INTO operation_status VALUES (4002, "Pierwszy test szczelności NOK ", "", 6);
INSERT OR REPLACE INTO operation_status VALUES (4003, "Drugi test szczelności OK ", "", 6);
INSERT OR REPLACE INTO operation_status VALUES (4004, "Drugi test szczelności OK ", "", 6);
INSERT OR REPLACE INTO operation_status VALUES (4005, "Pierwszy test szczelności PASS", "", 6);
INSERT OR REPLACE INTO operation_status VALUES (4010, "Pierwszy test szczelności RECLAIM", "", 6);
INSERT OR REPLACE INTO operation_status VALUES (4015, "Pierwszy test szczelności REJECT", "", 6);
INSERT OR REPLACE INTO operation_status VALUES (4020, "Pierwszy test szczelności OVERRUN", "", 6);
INSERT OR REPLACE INTO operation_status VALUES (4025, "Pierwszy test szczelności OVERPRESSURE", "", 6);
INSERT OR REPLACE INTO operation_status VALUES (4030, "Pierwszy test szczelności GROSSLEAK", "", 6);
INSERT OR REPLACE INTO operation_status VALUES (4045, "Drugi test szczelności PASS", "", 6);
INSERT OR REPLACE INTO operation_status VALUES (4050, "Drugi test szczelności RECLAIM", "", 6);
INSERT OR REPLACE INTO operation_status VALUES (4055, "Drugi test szczelności REJECT", "", 6);
INSERT OR REPLACE INTO operation_status VALUES (4060, "Drugi test szczelności OVERRUN", "", 6);
INSERT OR REPLACE INTO operation_status VALUES (4065, "Drugi test szczelności OVERPRESSURE", "", 6);
INSERT OR REPLACE INTO operation_status VALUES (4070, "Drugi test szczelności GROSSLEAK", "", 6);
INSERT OR REPLACE INTO operation_status VALUES (5000, "Brak", "", 0);
INSERT OR REPLACE INTO operation_status VALUES (5001, "Obecność kulki OK", "", 0);
INSERT OR REPLACE INTO operation_status VALUES (5002, "Pobranie i sprawdzenie uszczelki 1 OK", "", 0);
INSERT OR REPLACE INTO operation_status VALUES (5003, "Pobranie i sprawdzenie uszczelki 2 OK", "", 0);
INSERT OR REPLACE INTO operation_status VALUES (5004, "Pobranie i sprawdzenie płyty OK", "", 0);
INSERT OR REPLACE INTO operation_status VALUES (5005, "Pobranie sprężyny OK", "", 0);
INSERT OR REPLACE INTO operation_status VALUES (5100, "Brak", "", 0);
INSERT OR REPLACE INTO operation_status VALUES (5101, "Nieznany stop", "", 2);
INSERT OR REPLACE INTO operation_status VALUES (5102, "Flaga NOK", "", 2);
INSERT OR REPLACE INTO operation_status VALUES (5103, "Brak startu wkrętaka", "", 2);
INSERT OR REPLACE INTO operation_status VALUES (5104, "Osiągnięty max kąt", "", 2);
INSERT OR REPLACE INTO operation_status VALUES (5105, "Osiągnięty max moment", "", 2);
INSERT OR REPLACE INTO operation_status VALUES (5106, "Błąd testu systemu", "", 2);
INSERT OR REPLACE INTO operation_status VALUES (5107, "Błąd sekwencji programu", "", 2);
INSERT OR REPLACE INTO operation_status VALUES (5108, "Rezerwa", "", 2);
INSERT OR REPLACE INTO operation_status VALUES (5109, "Za mały moment", "", 2);
INSERT OR REPLACE INTO operation_status VALUES (5110, "Za duży moment", "", 2);
INSERT OR REPLACE INTO operation_status VALUES (5111, "Za mały kąt", "", 2);
INSERT OR REPLACE INTO operation_status VALUES (5112, "Za duży kąt", "", 2);
INSERT OR REPLACE INTO operation_status VALUES (5113, "Za długi czas wkręcania", "", 2);
INSERT OR REPLACE INTO operation_status VALUES (5114, "Puszczony start", "", 2);
INSERT OR REPLACE INTO operation_status VALUES (5115, "Błąd prądu", "", 2);
INSERT OR REPLACE INTO operation_status VALUES (5116, "Błąd zasilania", "", 2);
INSERT OR REPLACE INTO operation_status VALUES (5117, "Wkręcanie OK", "", 2);
INSERT OR REPLACE INTO operation_status VALUES (5201, "Nieznany stop", "", 3);
INSERT OR REPLACE INTO operation_status VALUES (5202, "Flaga NOK", "", 3);
INSERT OR REPLACE INTO operation_status VALUES (5203, "Brak startu wkrętaka", "", 3);
INSERT OR REPLACE INTO operation_status VALUES (5204, "Osiągnięty max kąt", "", 3);
INSERT OR REPLACE INTO operation_status VALUES (5205, "Osiągnięty max moment", "", 3);
INSERT OR REPLACE INTO operation_status VALUES (5206, "Błąd testu systemu", "", 3);
INSERT OR REPLACE INTO operation_status VALUES (5207, "Błąd sekwencji programu", "", 3);
INSERT OR REPLACE INTO operation_status VALUES (5208, "Rezerwa", "", 3);
INSERT OR REPLACE INTO operation_status VALUES (5209, "Za mały moment", "", 3);
INSERT OR REPLACE INTO operation_status VALUES (5210, "Za duży moment", "", 3);
INSERT OR REPLACE INTO operation_status VALUES (5211, "Za mały kąt", "", 3);
INSERT OR REPLACE INTO operation_status VALUES (5212, "Za duży kąt", "", 3);
INSERT OR REPLACE INTO operation_status VALUES (5213, "Za długi czas wkręcania", "", 3);
INSERT OR REPLACE INTO operation_status VALUES (5214, "Puszczony start", "", 3);
INSERT OR REPLACE INTO operation_status VALUES (5215, "Błąd prądu", "", 3);
INSERT OR REPLACE INTO operation_status VALUES (5216, "Błąd zasilania", "", 3);
INSERT OR REPLACE INTO operation_status VALUES (5217, "Wkręcanie OK", "", 3);
