INSERT OR REPLACE INTO operation_type VALUES (101, 'Prasowanie tulejek', '');
INSERT OR REPLACE INTO operation_type VALUES (201, 'Smarowanie', '');
INSERT OR REPLACE INTO operation_type VALUES (301, 'Referencjonowanie Promessa', '');
INSERT OR REPLACE INTO operation_type VALUES (302, 'Wciskanie kołka 1', '');
INSERT OR REPLACE INTO operation_type VALUES (303, 'Wciskanie kołka 2', '');
INSERT OR REPLACE INTO operation_type VALUES (304, 'Wciskanie kołka 3', '');
INSERT OR REPLACE INTO operation_type VALUES (305, 'Wciskanie kołka 4', '');
INSERT OR REPLACE INTO operation_type VALUES (306, 'Wciskanie kołka 5', '');
INSERT OR REPLACE INTO operation_type VALUES (307, 'Wciskanie kołka 6', '');
INSERT OR REPLACE INTO operation_type VALUES (308, 'Wciskanie kołka 7', '');
INSERT OR REPLACE INTO operation_type VALUES (309, 'Wciskanie kołka 8', '');
INSERT OR REPLACE INTO operation_type VALUES (310, 'Wciskanie kołka 9', '');
INSERT OR REPLACE INTO operation_type VALUES (311, 'Wciskanie kołka 10', '');
INSERT OR REPLACE INTO operation_type VALUES (401, 'Pierwszy test szczelności', '');
INSERT OR REPLACE INTO operation_type VALUES (402, 'Drugi test szczelności', '');
INSERT OR REPLACE INTO operation_type VALUES (501, 'Wkręcanie śruby zaworka', '');
INSERT OR REPLACE INTO operation_type VALUES (502, 'Wkręcanie dokładne śruby 1 zaworka', '');
INSERT OR REPLACE INTO operation_type VALUES (503, 'Wkręcanie wstępne śruby 2 zaworka', '');
INSERT OR REPLACE INTO operation_type VALUES (504, 'Wkręcanie dokładne śruby 2 zaworka', '');
INSERT OR REPLACE INTO operation_type VALUES (505, 'Wkręcanie wstępne śruby 3 zaworka', '');
INSERT OR REPLACE INTO operation_type VALUES (506, 'Wkręcanie dokładne śruby 3 zaworka', '');
INSERT OR REPLACE INTO operation_type VALUES (507, 'Wkręcanie wstępne śruby 4 zaworka', '');
INSERT OR REPLACE INTO operation_type VALUES (508, 'Wkręcanie dokładne śruby 4 zaworka', '');
INSERT OR REPLACE INTO operation_type VALUES (509, 'Wkręcanie śruby boczne gniazdo', '');
INSERT OR REPLACE INTO operation_type VALUES (510, 'Wkręcanie dokładne śruby 5 boczne gniazdo', '');
INSERT OR REPLACE INTO operation_type VALUES (511, 'Obecność kulki', '');
INSERT OR REPLACE INTO operation_type VALUES (512, 'Pobranie i sprawdzenie uszczelki 1', '');
INSERT OR REPLACE INTO operation_type VALUES (513, 'Pobranie i sprawdzenie uszczelki 2', '');
INSERT OR REPLACE INTO operation_type VALUES (514, 'Pobranie i sprawdzenie płyty', '');
INSERT OR REPLACE INTO operation_type VALUES (515, 'Pobranie sprężyny', '');